User management with PUID and PGID

diff --git a/source/entrypoint b/source/entrypoint
--- a/source/entrypoint
+++ b/source/entrypoint
@@ -1,11 +1,6 @@
 #!/bin/bash
 
-function wrapper() {
-  echo "Calling wrapper"
-  exec /wrapper
-  echo "Failed in call to wrapper"
-  exit 1
-}
+set -o pipefail
 
 # Current user and group ids
 USER_ID=$(id -u)
@@ -15,108 +10,69 @@ GROUP_ID=$(id -g)
 PUID="${PUID:-0}"
 PGID="${PGID:-0}"
 
+echo "USER_ID: $USER_ID"
+echo "GROUP_ID: $GROUP_ID"
+echo "PUID: $PUID"
+echo "PGID: $PGID"
+
 # Check if we could do any user management
 if [ "$USER_ID" != "0" ] ; then
   # Nothing we can do with user management as we're already another user. Just
   # call the wrapper
-  echo "Already another user ${USER_ID}:${GROUP_ID}"
-  wrapper
+  echo "Already non-root (${USER_ID}:${GROUP_ID}). No user management possible. Calling wrapper"
+  exec /wrapper
+  echo "Failed call to wrapper"
   exit 1
 fi
 
-# Check if we're already the correct user and group
-if [ "$USER_ID" == "$PUID" ] && [ "$GROUP_ID" == "$PGID" ] ; then
-  echo "Already target user and group ${PUID}:${PGID}"
-  wrapper
-  exit 1
-fi
-
-if [ "$USER_ID" != "$PUID" ] ; then
-fi
-
-# We're the root user and either the user id or group id is incorrect
-# Make sure the user and group entries exist
-echo "Adding oxidized group with GID $PGID"
-if ! groupadd -g "$PGID" -o oxidized ; then
-  echo "Could not create group"
-  exit 1
-fi
-echo "Group Entity: $(getent group oxidized)"
-
-echo "Adding oxidized user with UID $PUID"
-if ! useradd -u "${PUID}" -g "${PGID}" -M -d $HOME oxidized ; then
-  echo "Could not create user"
-  exit 1
-fi
-echo "User Entity: $(getent user oxidized)"
-
-# Create the group, if it doesn't exist
-if ! id -gn > /dev/null 2>&1 ; then
-  echo "Group does not have a passwd entry"
-  echo "Creating user account for current ID: ${USER_ID}:${GROUP_ID}"
-  if ! groupadd -g "$GROUP_ID" oxidized ; then
-    echo "Could not create group"
-    exit 1
-  fi
-  echo "User Entity: $(getent group oxidized)"
-fi
-
-if ! id -un > /dev/null 2>&1 ; then
-  echo "User does not have a passwd entry"
-  echo "Creating user account for current ID: ${USER_ID}:${GROUP_ID}"
-  if ! useradd -u "$USER_ID" -g "$GROUP_ID" -M -d $HOME oxidized ; then
-    echo "Could not create user account"
-    exit 1
-  fi
-  echo "User Entity: $(getent passwd oxidized)"
-fi
-
-
-# Create the oxidized directory
-echo "Creating oxidized root: $OXIDIZED_ROOT"
-if ! mkdir -p "$OXIDIZED_ROOT" ; then
-  echo "Failed to create oxidized directory"
-  exit 1
-fi
-
-# Attempt exclusive lock before continuing
-echo "Attempting exclusive lock on file: $LOCK_FILE"
-exec 4> "$LOCK_FILE"
-if ! flock -w 5 -x 4 ; then
-  echo "Could not get exclusive lock on $LOCK_FILE"
-  exit 1
-else
-  echo "Exclusive lock successful"
-fi
-
-# Remove the existing PID file
-echo "Removing PID file: $PID_FILE"
-if [ "$PID_FILE" != "" ] && [ -f "$PID_FILE" ] ; then
-  if ! rm -f "$PID_FILE" ; then
-    echo "Could not remove pid file: $PID_FILE"
+# Determine the target group name
+if ! TARGET_GROUP=$(getent group "${PGID}" | cut -f 1 -d ':') ; then
+  # Can't identify the name for the group, so we'll create one
+  echo "Target group doesn't exist. Creating"
+  if ! groupadd -g "${PGID}" oxidized ; then
+    echo "Failed to add oxidized group"
     exit 1
   fi
 else
-  echo "PID file ($PID_FILE) not found"
+  echo "Target group already exists"
 fi
 
-# Copy the source configuration, if present
-echo "Checking for config source: $SOURCE_CONFIG"
-if [ -f "$SOURCE_CONFIG" ] ; then
-  echo "Config found in $SOURCE_CONFIG"
-  if ! cp "$SOURCE_CONFIG" "$CONFIG_FILE" ; then
-    echo "Failed to copy configuration to $CONFIG_FILE"
+if ! TARGET_GROUP=$(getent group "${PGID}" | cut -f 1 -d ':') ; then
+  echo "Could not resolve $PGID to group name or create new group"
+  exit 1
+fi
+
+if [ "$TARGET_GROUP" == "" ] ; then
+  echo "Empty target group name"
+  exit 1
+fi
+echo "Target Group: $TARGET_GROUP"
+
+# Determine the target user name
+if ! TARGET_USER=$(getent passwd "${PUID}" | cut -f 1 -d ':') ; then
+  # Can't identify the name for the user, so we'll create one
+  echo "Target user doesn't exist. Creating."
+  if ! useradd -u "${PUID}" -g "${PGID}" -M -d $HOME oxidized ; then
+    echo "Failed to add oxidized user"
     exit 1
-  else
-    echo "Copied configuration to $CONFIG_FILE"
   fi
 else
-  echo "Did not find source config in $SOURCE_CONFIG"
+  echo "Target user already exists"
 fi
 
-# Execute oxidized
-exec /usr/local/bin/oxidized
+if ! TARGET_USER=$(getent passwd "${PUID}" | cut -f 1 -d ':') ; then
+  echo "Could not resolve $PUID to group name or create new group"
+  exit 1
+fi
 
-# Could not run oxidized, so exit with failure
-echo "Could not run oxidized"
+if [ "$TARGET_USER" == "" ] ; then
+  echo "Empty target group name"
+  exit 1
+fi
+echo "Target User: $TARGET_USER"
+
+# Call the wrapper
+echo "Running wrapper as ${TARGET_USER}:${TARGET_GROUP}"
+exec su -g "${TARGET_GROUP}" -c /wrapper "${TARGET_USER}"
+echo "Failed call to wrapper"
 exit 1
