User management

diff --git a/source/entrypoint b/source/entrypoint
--- a/source/entrypoint
+++ b/source/entrypoint
@@ -1,55 +1,78 @@
 #!/bin/bash
 
-OXIDIZED_ROOT="$HOME/.config/oxidized"
-SOURCE_CONFIG="$HOME/config"
-CONFIG_FILE="$OXIDIZED_ROOT/config"
-LOCK_FILE=/tmp/entrypoint_lock
+set -o pipefail
 
-# Create the oxidized directory
-echo "Creating oxidized root: $OXIDIZED_ROOT"
-if ! mkdir -p "$OXIDIZED_ROOT" ; then
-  echo "Failed to create oxidized directory"
+# Current user and group ids
+USER_ID=$(id -u)
+GROUP_ID=$(id -g)
+
+# Allow override of the user we'll run as. Default to root
+PUID="${PUID:-0}"
+PGID="${PGID:-0}"
+
+echo "USER_ID: $USER_ID"
+echo "GROUP_ID: $GROUP_ID"
+echo "PUID: $PUID"
+echo "PGID: $PGID"
+
+# Check if we could do any user management
+if [ "$USER_ID" != "0" ] ; then
+  # Nothing we can do with user management as we're already another user. Just
+  # call the wrapper
+  echo "Already non-root (${USER_ID}:${GROUP_ID}). No user management possible. Calling wrapper"
+  exec /wrapper
+  echo "Failed call to wrapper"
   exit 1
 fi
 
-# Attempt exclusive lock before continuing
-echo "Attempting exclusive lock on file: $LOCK_FILE"
-exec 4> "$LOCK_FILE"
-if ! flock -w 5 -x 4 ; then
-  echo "Could not get exclusive lock on $LOCK_FILE"
+# Determine the target group name
+if ! TARGET_GROUP=$(getent group "${PGID}" | cut -f 1 -d ':') ; then
+  # Can't identify the name for the group, so we'll create one
+  echo "Target group doesn't exist. Creating"
+  if ! groupadd -g "${PGID}" oxidized ; then
+    echo "Failed to add oxidized group"
+    exit 1
+  fi
+else
+  echo "Target group already exists"
+fi
+
+if ! TARGET_GROUP=$(getent group "${PGID}" | cut -f 1 -d ':') ; then
+  echo "Could not resolve $PGID to group name or create new group"
   exit 1
-else
-  echo "Exclusive lock successful"
 fi
 
-# Remove the existing PID file
-echo "Removing PID file: $PID_FILE"
-if [ "$PID_FILE" != "" ] && [ -f "$PID_FILE" ] ; then
-  if ! rm -f "$PID_FILE" ; then
-    echo "Could not remove pid file: $PID_FILE"
+if [ "$TARGET_GROUP" == "" ] ; then
+  echo "Empty target group name"
+  exit 1
+fi
+echo "Target Group: $TARGET_GROUP"
+
+# Determine the target user name
+if ! TARGET_USER=$(getent passwd "${PUID}" | cut -f 1 -d ':') ; then
+  # Can't identify the name for the user, so we'll create one
+  echo "Target user doesn't exist. Creating."
+  if ! useradd -u "${PUID}" -g "${PGID}" -M -d $HOME oxidized ; then
+    echo "Failed to add oxidized user"
     exit 1
   fi
 else
-  echo "PID file ($PID_FILE) not found"
+  echo "Target user already exists"
 fi
 
-# Copy the source configuration, if present
-echo "Checking for config source: $SOURCE_CONFIG"
-if [ -f "$SOURCE_CONFIG" ] ; then
-  echo "Config found in $SOURCE_CONFIG"
-  if ! cp "$SOURCE_CONFIG" "$CONFIG_FILE" ; then
-    echo "Failed to copy configuration to $CONFIG_FILE"
-    exit 1
-  else
-    echo "Copied configuration to $CONFIG_FILE"
-  fi
-else
-  echo "Did not find source config in $SOURCE_CONFIG"
+if ! TARGET_USER=$(getent passwd "${PUID}" | cut -f 1 -d ':') ; then
+  echo "Could not resolve $PUID to group name or create new group"
+  exit 1
 fi
 
-# Execute oxidized
-exec /usr/local/bin/oxidized
+if [ "$TARGET_USER" == "" ] ; then
+  echo "Empty target group name"
+  exit 1
+fi
+echo "Target User: $TARGET_USER"
 
-# Could not run oxidized, so exit with failure
-echo "Could not run oxidized"
+# Call the wrapper
+echo "Running wrapper as ${TARGET_USER}:${TARGET_GROUP}"
+exec su -g "${TARGET_GROUP}" -c /wrapper "${TARGET_USER}"
+echo "Failed call to wrapper"
 exit 1
